name: dhahar_lib_driver
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  shared_preferences: ^2.5.3
  connectivity_plus: ^6.1.5
  firebase_core: ^4.1.0
  firebase_messaging: ^16.0.1
  flutter_local_notifications: ^19.4.1
  firebase_auth: ^6.0.2
  path_provider: ^2.1.5
  url_strategy: ^0.3.0
  pin_code_fields: ^8.0.1
  http: ^1.5.0
  flutter_switch: ^0.3.2
  shimmer_animation: ^2.2.2
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  google_maps_flutter: ^2.13.1
  url_launcher: ^6.3.2
  vibration: ^3.1.3
  image_picker: ^1.2.0
  phone_numbers_parser: ^9.0.11
  country_code_picker: ^3.4.0
  audioplayers: ^6.5.1
  flutter_widget_from_html_core: ^0.17.0
  intl: ^0.20.2
  path: ^1.9.1
  http_parser: ^4.1.2
  dotted_border: ^3.1.0
  photo_view: ^0.15.0
  flutter_inappwebview: ^6.1.5
  file_picker: ^10.3.2
  flutter_svg: ^2.2.1
  video_player: ^2.10.0
  chewie: ^1.12.1
  permission_handler: ^12.0.1
  flutter_foreground_task: ^9.1.0
  just_the_tooltip: ^0.0.12
  location: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/
    - assets/notification.mp3
    - assets/json/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900